---
title: "My first dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(viridis)
library(p8105.datasets)
library(plotly)

# rmarkdown::render("dashboard.rmd", output_format = "flexdashboard::flex_dashboard")
```

```{r}
set.seed(1)

food = 
  rest_inspec %>% 
  janitor::clean_names() %>%
  drop_na() %>% 
  sample_n(5000)
```


Column {data-width=650}
-----------------------------------------------------------------------

### Visualizing Chipotle's Inspection Results Across Time

```{r}
food %>% 
  select(dba, inspection_date, score, grade, street) %>%
  filter(dba == "CHIPOTLE MEXICAN GRILL") %>%
  mutate(text_label = str_c("Location: ", street, ", Grade: ", grade)) %>%
  plot_ly(x = ~inspection_date, y = ~score, type = "scatter", mode = "markers", text = ~text_label, color = ~grade, alpha = 0.5)
```


Column {data-width=350}
-----------------------------------------------------------------------

### Boxplot of Food Inspection Scores by Cuisine

```{r}
food %>%  
  select(cuisine_description, score) %>%
  filter(cuisine_description %in% c("Brazilian", "Portugese", "American", "Creole", "Greek", "Indian", "Italian", "Japanese", "Thai", "Iranian", "Mexican", "French", "Carribean", "Chinese", "Spanish")) %>%
  mutate(cuisine_description = fct_reorder(cuisine_description, score)) %>% 
  plot_ly(y = ~score, color = ~cuisine_description, type = "box",
          colors = "Set2")
```

### Count of Critical violations by Borough

```{r}
# histogram of critical violations by borough
food %>%  
  select(critical_flag, boro) %>%
  filter(critical_flag == "Critical") %>%
  group_by(boro) %>%
  count(critical_flag) %>% 
  ungroup(boro) %>%
  mutate(boro = fct_reorder(boro, n)) %>% 
  plot_ly(x = ~boro, y = ~n, color = ~boro, type = "bar")
```

